#!/usr/bin/python2

import sys, re
from getopt import getopt
from phue import Bridge

config = {}

class Hue():
    def __init__(self, bridge, lightbulb=None, group=None):
        self.bridgeAddress = bridge

        if lightbulb:
            self.lightbulbs = re.split('\s*,\s*', lightbulb)

        if group:
            self.groups = dict(
                map(lambda _: (_, True), re.split('\s*,\s*', group))
            )

    def connect(self):
        self.bridge = Bridge(self.bridgeAddress)
        self.bridge.connect()
        self.bridge.get_api()

        if hasattr(self, 'groups'):
            for group in self.bridge.groups:
                if group.name in self.groups:
                    if not hasattr(self, 'lightbulbs'):
                        self.lightbulbs = []

                    self.lightbulbs.extend(list(
                        map(lambda light: light.name, group.lights)
                    ))

        if not hasattr(self, 'lightbulbs'):
            self.lightbulbs = []
            for light in self.bridge.lights:
                self.lightbulbs.append(light.name)

    def setOn(self, on):
        self.bridge.set_light(self.lightbulbs, 'on', on)

    def toggle(self):
        state = False
        for light in self.lightbulbs:
            if not self.bridge.get_light(light, 'on'):
                state = True
                break

        self.bridge.set_light(self.lightbulbs, 'on', state)

    def setBri(self, bri):
        if bri == 0:
            self.bridge.set_light(self.lightbulbs, 'on', False)
        else:
            self.bridge.set_light(self.lightbulbs, 'on', True)
        self.bridge.set_light(self.lightbulbs, 'bri', bri)

    def setSat(self, sat):
        self.bridge.set_light(self.lightbulbs, 'sat', sat)

    def setHue(self, hue):
        self.bridge.set_light(self.lightbulbs, 'hue', hue)

def showHelp():
    print "Usage: %s <-b|--bridge> bridge [-l|--lightbulb lighbulb] [-g|--group group] [--on|--off|--toggle] [--bri <brightness>] [--sat <saturation>] [--hue <hue>]\n" \
        "  -b|--bridge\tIP address or hostname of the Philips Hue bridge\n" \
        "  -l|--lightbulb\tLightbulbs to toggle, name or index, or comma separated list (default: all)\n" \
        "  -g|--group\tRoom or group of lights to toggle, name or index, or comma separated list (default: all)\n" \
        "  --on|--off|--toggle\tSet the lights on or off, or toggles the state\n" \
        "  --bri <brightness>\tSet the lights brightness [0-255]\n" \
        "  --sat <saturation>\tSet the lights saturation [0-500]\n" \
        "  --hue <hue>\tSet the lights hue [0-65535]\n" \
        % (sys.argv[0])

def initConfig():
    optlist, args = getopt(sys.argv[1:], 'b:l:g:', ['bridge=', 'lightbulb=', 'group=', 'on', 'off', 'toggle', 'bri=', 'hue=', 'sat='])

    for opt in optlist:
        if opt[0] == '-b' or opt[0] == '--bridge':
            config['bridge'] = opt[1]
        elif opt[0] == '-l' or opt[0] == '--lightbulb':
            config['lightbulb'] = opt[1]
        elif opt[0] == '-g' or opt[0] == '--group':
            config['group'] = opt[1]
        elif opt[0] == '--toggle':
            config['toggle'] = True
        elif opt[0] == '--on':
            config['on'] = True
        elif opt[0] == '--off':
            config['on'] = False
        elif opt[0] == '--bri':
            config['bri'] = int(opt[1])
        elif opt[0] == '--sat':
            config['sat'] = int(opt[1])
        elif opt[0] == '--hue':
            config['hue'] = int(opt[1])
        else:
            showHelp()
            sys.exit(1)

    if 'bridge' not in config:
        showHelp()
        sys.exit(1)

    if \
            'toggle'  not in config and \
            'on'  not in config and \
            'bri' not in config and \
            'sat' not in config and \
            'hue' not in config:
        showHelp()
        sys.exit(1)

def main():
    initConfig()

    hue = Hue(bridge=config['bridge'],
              lightbulb = (config['lightbulb'] if 'lightbulb' in config else None),
              group = (config['group'] if 'group' in config else None))
    hue.connect()

    if 'toggle' in config:
        hue.toggle()
        return

    if 'on' in config:
        hue.setOn(config['on'])
    if 'bri' in config:
        hue.setBri(config['bri'])
    if 'sat' in config:
        hue.setSat(config['sat'])
    if 'hue' in config:
        hue.setHue(config['hue'])

if __name__ == "__main__":
    main()

